import Header from "@/components/Header";
import type { Metadata } from "next";
import Cards from "@/components/Cards";
import Table from "@/components/Table";

export default function Home() {
  return (
    <>
      <Header />
      <div className="content-container px-4 py-4">
        <Cards />
        <Table />
      </div>
    </>
  );
}

export const metadata: Metadata = {
  title: "WeFrameTech",
  description: "Generated by create next app",
};