import Header from "@/components/Header";
import type { Metadata } from "next";

export default function Home() {
  return (
    <>
    <Header />
    </>
  );
}


export const metadata: Metadata = {
  title: "WeFrameTech",
  description: "Generated by create next app",
};