import Header from "@/components/Header";
import type { Metadata } from "next";
import Cards from "@/components/Cards";
import Table from "@/components/Table";

export default function Home() {
  return (
    <>
      <div className="h-screen overflow-y-scroll">
        <Header />

        <div className="content-container sm:px-4 py-4">
          <Cards />
          <Table />
        </div>

      </div>
    </>
  );
}

export const metadata: Metadata = {
  title: "WeFrameTech",
  description: "Generated by create next app",
};